param(
    [string]$ModuleRoot = (Split-Path -Parent $PSScriptRoot),
    [string]$AssemblyPath = ''
)

$ErrorActionPreference = 'Stop'

function Assert-True([bool]$Condition, [string]$Message) {
    if (-not $Condition) {
        throw $Message
    }
}

if ([string]::IsNullOrWhiteSpace($AssemblyPath)) {
    $AssemblyPath = Join-Path $ModuleRoot 'bin\AgesOfCalradia_Test_Win64_Shipping_Client\AgesOfCalradia.dll'
}

$borderPath = Join-Path $ModuleRoot 'CampaignKingdomBorderBehavior.cs'
$territoryFillPath = Join-Path $ModuleRoot 'CampaignPoliticalTerritoryFill.cs'
$terrainGridPath = Join-Path $ModuleRoot 'CampaignMapTerrainGridCache.cs'
$strategicLandMaskPath = Join-Path $ModuleRoot 'CampaignStrategicLandMask.cs'
$politicalOverlayPath = Join-Path $ModuleRoot 'CampaignPoliticalOverlayView.cs'
$strategicKingdomLabelsPath = Join-Path $ModuleRoot 'CalendarStrategicKingdomLabels.cs'
$strategicFriendlyArmiesPath = Join-Path $ModuleRoot 'CalendarStrategicFriendlyArmies.cs'
$politicalLabelPrefabPath = Join-Path $ModuleRoot 'GUI\Prefabs\Map\PoliticalKingdomLabel.xml'
$worldCalendarScreenPath = Join-Path $ModuleRoot 'WorldCalendarScreen.cs'
$subModulePath = Join-Path $ModuleRoot 'MySubModule.cs'
$projectPath = Join-Path $ModuleRoot 'TwelveMonthCalendar.csproj'
$ledgerPath = Join-Path $ModuleRoot 'CalendarWorldLedgerVM.cs'
$prefabPath = Join-Path $ModuleRoot 'GUI\Prefabs\WorldCalendar\WorldCalendar.xml'

Assert-True (Test-Path -LiteralPath $borderPath) 'Campaign border behavior source is missing.'
Assert-True (Test-Path -LiteralPath $territoryFillPath) 'Campaign political territory fill source is missing.'
Assert-True (Test-Path -LiteralPath $terrainGridPath) 'Shared campaign terrain-grid cache source is missing.'
Assert-True (Test-Path -LiteralPath $strategicLandMaskPath) 'Campaign strategic land-mask source is missing.'
Assert-True (Test-Path -LiteralPath $politicalOverlayPath) 'Campaign political overlay view source is missing.'
Assert-True (Test-Path -LiteralPath $strategicKingdomLabelsPath) 'Strategic Map kingdom-label source is missing.'
Assert-True (Test-Path -LiteralPath $strategicFriendlyArmiesPath) 'Strategic Map friendly-army source is missing.'
Assert-True (Test-Path -LiteralPath $politicalLabelPrefabPath) 'Campaign political kingdom-label prefab is missing.'
Assert-True (Test-Path -LiteralPath $AssemblyPath) "Compiled test assembly is missing: $AssemblyPath"

$borderSource = Get-Content -LiteralPath $borderPath -Raw
$territoryFillSource = Get-Content -LiteralPath $territoryFillPath -Raw
$terrainGridSource = Get-Content -LiteralPath $terrainGridPath -Raw
$strategicLandMaskSource = Get-Content -LiteralPath $strategicLandMaskPath -Raw
$politicalOverlaySource = Get-Content -LiteralPath $politicalOverlayPath -Raw
$strategicKingdomLabelsSource = Get-Content -LiteralPath $strategicKingdomLabelsPath -Raw
$strategicFriendlyArmiesSource = Get-Content -LiteralPath $strategicFriendlyArmiesPath -Raw
$politicalLabelPrefabSource = Get-Content -LiteralPath $politicalLabelPrefabPath -Raw
$worldCalendarScreenSource = Get-Content -LiteralPath $worldCalendarScreenPath -Raw
$subModuleSource = Get-Content -LiteralPath $subModulePath -Raw
$projectSource = Get-Content -LiteralPath $projectPath -Raw
$ledgerSource = Get-Content -LiteralPath $ledgerPath -Raw
$prefabSource = Get-Content -LiteralPath $prefabPath -Raw

Assert-True ($borderSource -match 'class CampaignKingdomBorderBehavior : CampaignBehaviorBase') 'Campaign border behavior is not a CampaignBehaviorBase.'
Assert-True ($borderSource -match 'OnSettlementOwnerChangedEvent' -and $borderSource -match 'DailyTickEvent') 'Campaign borders are missing ownership or daily refresh hooks.'
Assert-True ($borderSource -match 'PoliticalTerritoryCell' -and $territoryFillSource -match 'NearestSiteIndex') 'Campaign political fill is missing spatially indexed nearest-settlement ownership calculation.'
Assert-True ($borderSource -notmatch 'ClipCell|ClipPolygon' -and $territoryFillSource -notmatch 'Polygon') 'Unused exact Voronoi polygon construction remains in the grid renderer.'
Assert-True ($borderSource -notmatch 'RenderEdges|AddLineRibbon|_politicalBorderAlpha|BorderMaterial' -and $territoryFillSource -match 'FrontierSubdivisions = 4' -and $territoryFillSource -match 'FrontierCoastRefinementDepth = 1' -and $territoryFillSource -match 'BuildFrontierCell' -and $territoryFillSource -match 'FrontierMeshRenderOrder = 108' -and $territoryFillSource -match 'FrontierWidth = 1\.6f' -and $territoryFillSource -match 'FrontierSideSampleDistance = 2\.75f' -and $territoryFillSource -match 'FrontierLandSupportSampleDistance = 1f' -and $territoryFillSource -match 'coastSide != currentCoastSide' -and $territoryFillSource -match 'FrontierCapStepsPerHalf = 4' -and $territoryFillSource -match 'FrontierBrightnessPercent = 85u' -and $territoryFillSource -match 'HashSet<FrontierPointKey>' -and $territoryFillSource -match '_frontierCapPoints\.Add' -and $territoryFillSource -match 'AddSplitRoundCapIfNew' -and $territoryFillSource -match 'GetFrontierSideColor' -and $territoryFillSource -match 'ScaleOpaqueColor' -and $territoryFillSource -match 'AddDoubleSidedQuad' -and $territoryFillSource -match 'AddHalfRoundCap' -and $territoryFillSource -match 'OwnerKey' -and $borderSource -match 'frontierSegments=' -and $borderSource -match 'frontierCoastRefinedCells=' -and $borderSource -match 'frontierEntities=') 'Thin, contrasting, non-overlapping, connected two-sided live-faction frontiers are not independently sampled and audited.'
Assert-True ($territoryFillSource -match 'crossings\.Count == 4' -and $territoryFillSource -match 'centerMatchesLowerLeft' -and $territoryFillSource -match 'HasFrontierLandSupport' -and $territoryFillSource -match 'if \(!left\.Land && !right\.Land\) return false') 'Faction frontiers do not resolve saddle cells or reject unsupported chords across open water.'
Assert-True ($terrainGridSource -match 'GetNativeWaterTopologyDiagnostic' -and $territoryFillSource -match 'FrontierExteriorWaterMidpointCount' -and $territoryFillSource -match 'FrontierSameOwnerWaterChordRejectionCount' -and $territoryFillSource -match 'same-owner-water-chord' -and $territoryFillSource -match 'RecordFrontierSegmentDiagnostic' -and $territoryFillSource -match 'RecordFrontierCellDiagnostic' -and $borderSource -match 'frontierSameOwnerWaterChordRejects=' -and $borderSource -match 'frontierBridgeDiagnostics=') 'Frontier bridge diagnostics are missing from the mesh-generation path.'
Assert-True ($terrainGridSource -match 'IsFrontierLandExact\(Vec2 point\)' -and $terrainGridSource -match 'nativeTerrain == TerrainType\.Water && !enclosedAuthoredWater' -and $territoryFillSource -match 'CampaignMapTerrainGridCache\.IsFrontierLandExact\(point\)') 'Frontier topology does not keep generic-water channels separate from the political fill river-recovery path.'
Assert-True ($borderSource -notmatch 'ArtemsBetterUIVisuals|ArtemOwnsCampaignBorders') 'Campaign border rendering must remain owned by this module.'
Assert-True ($territoryFillSource -match 'FillMaterial = "vertex_color_mat"' -and $territoryFillSource -match 'FillAlpha = 0xFF000000u' -and $territoryFillSource -match 'FillBrightnessPercent = 50u' -and $territoryFillSource -match 'PoliticalFillMaximumOpacity = 1f' -and $territoryFillSource -match 'ScaleOpaqueColor\(owner\.Color, FillBrightnessPercent\)' -and $territoryFillSource -notmatch 'FillSaturationPercent|ScaleSaturatedOpaqueColor' -and $borderSource -match '_politicalLayerAlpha \* CampaignPoliticalTerritoryFill\.PoliticalFillMaximumOpacity' -and $territoryFillSource -match 'AddTriangle') 'Zoomed-out political territory fills do not preserve the original faction hues at a dark opaque value.'
Assert-True ($terrainGridSource -match 'GridColumns = 96' -and $terrainGridSource -match 'WorkBudgetMilliseconds = 5d' -and $terrainGridSource -match 'GetTerrainHeightAndNormal') 'Political terrain sampling is not using the recovered 96-column adaptive base grid and frame budget.'
Assert-True ($terrainGridSource -match 'TerrainSampleCount \{ get \{ return _rows \* GridColumns; \} \}' -and $terrainGridSource -match 'GetCellTerrain') 'Political terrain classification must retain a bounded shared coarse grid.'
Assert-True ($strategicLandMaskSource -match 'strategic_province_index\.png' -and $strategicLandMaskSource -match 'TryGetCampaignToReferenceProjection' -and $strategicLandMaskSource -match 'Marshal\.Copy') 'Political coast classification is not derived efficiently from the calibrated module-owned strategic province index.'
Assert-True ($strategicLandMaskSource -match 'NarrowChannelRadiusPixels = 32' -and $strategicLandMaskSource -match 'ElevatedChannelRadiusPixels = 96' -and $strategicLandMaskSource -match 'HasOpposingLand' -and $strategicLandMaskSource -match 'terrainHeight <= openSeaHeightCeiling' -and $strategicLandMaskSource -match 'openSeaHeightCeiling \+ ElevatedInteriorHeightMargin') 'Political land masking does not separate elevated opposing-bank channels from low open sea.'
Assert-True ($strategicLandMaskSource -match 'IsAuthoredLand\(Vec2 campaignPosition\)' -and $strategicLandMaskSource -match 'if \(IsLandPixel\(x, y\)\) return true;[\s\S]{0,100}terrainHeight <= openSeaHeightCeiling' -and $terrainGridSource -match 'strictAuthoredLand = _landMask\.IsAuthoredLand\(point\)' -and $terrainGridSource -match 'if \(!strictAuthoredLand \|\| IsCoarseProtectedWater\(point\)\)') 'Recovered narrow gaps are not exact-checked to keep sea-level channels between islands separate.'
Assert-True ($strategicLandMaskSource -match 'BuildEnclosedWater' -and $strategicLandMaskSource -match 'Queue<int>' -and $strategicLandMaskSource -match 'TopologySeparatorRadiusPixels = 4' -and $strategicLandMaskSource -match 'IsTopologyLandPixel' -and $strategicLandMaskSource -match 'IsEnclosedWater\(Vec2 campaignPosition\)' -and $terrainGridSource -match 'enclosedAuthoredWater = _landMask\.IsEnclosedWater\(point\)' -and $terrainGridSource -match 'strictAuthoredLand \|\| enclosedAuthoredWater') 'Enclosed authored lakes are not distinguished from edge-connected sea for political fill.'
Assert-True ($terrainGridSource -match 'FinalizeInteriorWaterTopology' -and $terrainGridSource -match 'Queue<int>' -and $terrainGridSource -match '_interiorWaterCells' -and $terrainGridSource -match 'IsNativeWaterTerrain\(terrain\)' -and $terrainGridSource -match 'IsInteriorWaterAt\(point\)') 'Native terrain-water topology does not distinguish enclosed lakes from edge-connected sea.'
Assert-True ($terrainGridSource -match 'if \(interiorNativeWater[\s\S]{0,160}!coarseProtectedWater' -and $terrainGridSource -match '!interiorNativeWater && IsProtectedWater\(nativeTerrain\)') 'An enclosed native-water component is still overridden by its coastal-sea terrain label.'
Assert-True ($terrainGridSource -match 'NativeTopologyColumns = GridColumns \* 4' -and $terrainGridSource -match 'SampleNextNativeTopology' -and $terrainGridSource -match 'IsExteriorNativeWaterAt' -and $terrainGridSource -match 'ExteriorNativeWaterFillRejectionCount' -and $terrainGridSource -match 'ExteriorNativeWaterFrontierRejectionCount' -and $terrainGridSource -match 'InteriorNativeWaterComponentCount' -and $terrainGridSource -match 'MarkInteriorNativeWaterComponent' -and $terrainGridSource -match 'InteriorNativeWaterFillAcceptanceCount' -and $terrainGridSource -match 'InteriorNativeWaterFrontierAcceptanceCount' -and $territoryFillSource -match 'FrontierUnsupportedSegmentCount' -and $territoryFillSource -match 'FrontierProjectionRejectedSegmentCount' -and $borderSource -match 'nativeTopologySamples=' -and $borderSource -match 'exteriorNativeWaterFillRejects=' -and $borderSource -match 'interiorNativeWaterComponents=' -and $borderSource -match 'frontierUnsupported=') 'Map-water topology and unsupported frontier diagnostics are missing.'
Assert-True ($terrainGridSource -match 'GetTerrainTypeAtPosition' -and $terrainGridSource -match 'IsProtectedWater' -and $terrainGridSource -match 'terrain != TerrainType\.Water' -and $terrainGridSource -match 'terrain == TerrainType\.CoastalSea' -and $terrainGridSource -match 'terrain == TerrainType\.OpenSea' -and $terrainGridSource -notmatch 'return terrain != TerrainType\.Lake' -and $terrainGridSource -notmatch 'return terrain == TerrainType\.Lake') 'Native lakes must receive political fill while generic water uses inland recovery and sea terrain remains protected.'
Assert-True ($terrainGridSource -match 'campaignPoint\.Face\.IsValid\(\)' -and $terrainGridSource -notmatch 'campaignPoint\.IsValid\(\)' -and $terrainGridSource -match 'IsCoarseProtectedWater' -and $borderSource -match 'exactProtectedWaterRejections=') 'Terrain classification must test face existence rather than movement validity and recheck refined authored coast samples inside protected-water cells.'
Assert-True ($territoryFillSource -match 'RiverMeshRenderOrder = 100' -and $territoryFillSource -match 'enclosedWaterMesh' -and $territoryFillSource -match 'EnclosedWaterCapLift = 4f' -and $territoryFillSource -match 'CampaignMapTerrainGridCache\.IsInteriorWaterAt\(center\)' -and $territoryFillSource -match 'AddRowEntity\(scene, riverMesh, forceDecals: false, riverCap: true\)' -and $territoryFillSource -notmatch 'GetWaterLevelAtPosition|RaiseTriangleToRiverSurface' -and $borderSource -match 'riverTriangles=' -and $borderSource -match 'enclosedWaterTriangles=' -and $borderSource -match 'riverEntities=') 'Native river and enclosed-water triangles must use isolated caps without forcing water decals above them.'
Assert-True ($terrainGridSource -match 'internal static bool IsExteriorNativeWaterAt' -and $territoryFillSource -match 'TouchesExteriorWater' -and $territoryFillSource -match 'ExteriorWaterTriangleRejectionCount' -and $borderSource -match 'exteriorWaterTriangleRejects=') 'Political fill triangles can still span edge-connected water between islands.'
Assert-True (($territoryFillSource + $borderSource + $politicalOverlaySource) -notmatch 'campaign_political_land_mask|CampaignPoliticalTerritoryFill\.LandMask|GetHeightAtPoint') 'Campaign political rendering still depends on the obsolete generated mask or blocking per-point height API.'
Assert-True ($borderSource -match 'landSamples=' -and $borderSource -match 'seaSamples=' -and $borderSource -match 'meshMilliseconds=' -and $borderSource -match 'heightNativeMilliseconds=' -and $borderSource -match 'exactHeightNativeMilliseconds=') 'Political coast and timing diagnostics are incomplete.'
Assert-True ($territoryFillSource -match 'NearestSiteIndex' -and $territoryFillSource -match 'axisDistance \* axisDistance < nearestDistance' -and $territoryFillSource -match 'RenderedTriangleCount' -and $borderSource -match 'triangles=') 'Political grid cells are not assigned through the spatial nearest-owner index with coverage diagnostics.'
Assert-True ($territoryFillSource -match 'MaximumRefinementDepth = 2' -and $territoryFillSource -match 'TerrainReliefRefinementThreshold = 0\.75f' -and $territoryFillSource -match 'TrySampleExactHeight' -and $territoryFillSource -match 'TerrainReliefRefinedCellCount' -and $territoryFillSource -match 'CrossesVisualBoundary' -and $territoryFillSource -match 'AddAdaptiveCell') 'The two-level political boundary and terrain-relief refinement is missing.'
Assert-True ($borderSource -match 'IsMapReady' -and $borderSource -match 'BeginOrAdvance' -and $borderSource -match 'if \(!RebuildBorders\(\)\) return') 'Political mesh construction is not deferred until the map is ready and the time-sliced cache completes.'
Assert-True ($borderSource -match 'SetPoliticalOverlayAlpha' -and $borderSource -match 'PoliticalTerritoryCell') 'Political fills are not integrated with the live Voronoi ownership cells.'
Assert-True ($borderSource -match 'CampaignPoliticalTerritoryFill\.Begin\(' -and $borderSource -match '_pendingFillBuilder\.Advance\(' -and $borderSource -match '_pendingFillBuilder\.IsFillComplete' -and $borderSource -match 'ReplacePoliticalFillEntities' -and $borderSource -match 'ReplacePoliticalFrontierEntities' -and $territoryFillSource -match 'TakeFillEntities\(\)' -and $territoryFillSource -match 'TakeFrontierEntities\(\)' -and $borderSource -match 'Campaign political fill published before frontier completion' -and $borderSource -match 'maximumBatchMilliseconds=') 'Campaign political fill is not published independently before bounded frontier completion.'
Assert-True ($territoryFillSource -match 'int row = _nextRow\+\+' -and $territoryFillSource -match 'GameEntity\.CreateEmpty' -and $territoryFillSource -match 'mesh\.AddTriangle\(first, third, second') 'Political fill batches must submit one bounded double-sided row per map frame.'
Assert-True ($terrainGridSource -match '_completedTimestamp' -and $terrainGridSource -match '_completedTimestamp > 0') 'Terrain-grid diagnostics must freeze completion time instead of including later mesh work.'
Assert-True ($terrainGridSource -match 'PrepareOpenSeaHeightCeiling' -and $terrainGridSource -match 'Median\(perimeterWaterHeights\)' -and $terrainGridSource -match 'medianDeviation \* 3f' -and $borderSource -match 'openSeaHeightSamples=') 'Open-sea recovery must use robust perimeter elevation statistics with runtime diagnostics.'
Assert-True ($territoryFillSource -match 'MaximumRowsPerFrame = 8' -and $territoryFillSource -match 'FrameBudgetMilliseconds = 4d' -and $territoryFillSource -match 'frameTimer\.Elapsed\.TotalMilliseconds') 'Higher-resolution political rows are not bounded by count and wall time per visible map frame.'
Assert-True ($terrainGridSource -match 'ElevatedRecoveryCellCount' -and $terrainGridSource -match 'RetainedWaterCellCount' -and $borderSource -match 'elevatedRecoveryCells=') 'Political channel recovery does not expose auditable land/water classification counters.'
Assert-True ($strategicLandMaskSource -match 'ElevatedInteriorHeightMargin = 2\.5f' -and $strategicLandMaskSource -match 'openSeaHeightCeiling \+ ElevatedInteriorHeightMargin' -and $borderSource -match 'nativeWaterCells=') 'Elevated inland-water recovery and native terrain diagnostics are missing.'
Assert-True ($territoryFillSource -match 'entity\.SetVisibilityExcludeParents\(false\)' -and $territoryFillSource -match 'entity\.SetReadyToRender\(true\)' -and $territoryFillSource -match 'CloseZoomFrontierDrop = 4\.65f' -and $borderSource -match 'ApplyPoliticalEntityVisibility' -and $borderSource -match 'ApplyFrontierZoomPresentation' -and $borderSource -match 'frame\.origin\.z = -CampaignPoliticalTerritoryFill\.CloseZoomFrontierDrop' -and $borderSource -match 'entity\.SetAlpha\(1f\)' -and $borderSource -match '_politicalFrontierEntities' -and $borderSource -notmatch 'entity\.SetReadyToRender\(false\)') 'Political fill must use reversible zoom visibility while coast-following faction frontiers remain opaque and z-fight-safe at normal zoom.'
Assert-True ($territoryFillSource -match 'PoliticalMeshRenderOrder = 100' -and $territoryFillSource -match 'RiverMeshRenderOrder = 100' -and $territoryFillSource -match 'FrontierMeshRenderOrder = 108' -and $territoryFillSource -match 'FrontierHeight = 5f' -and $territoryFillSource -match 'AddRowEntity\(scene, landMesh, forceDecals: false, riverCap: false\)' -and $territoryFillSource -match 'SetForceDecalsToRender\(false\)') 'Political land, river caps, and faction frontiers do not preserve their required terrain-pass ordering.'
Assert-True ($politicalOverlaySource -match '_behavior\?\.OnMapFrame\(camera\)' -and $borderSource -match 'internal void OnMapFrame\(Camera camera\)' -and $borderSource -notmatch 'private void OnTick\(float dt\)[\s\S]{0,400}RebuildBorders') 'Political preparation must advance from the map frame loop even while campaign time is paused.'
Assert-True ($politicalOverlaySource -match 'HasVisiblePoliticalFill') 'Kingdom labels must remain hidden until a political fill is ready.'
Assert-True ($borderSource -match 'BuildOwnershipSignature' -and $borderSource -match '_lastOwnershipSignature' -and $borderSource -notmatch 'private void OnDailyTick\(\)\s*\{\s*_dirty = true;') 'The expensive political terrain mesh must not rebuild unconditionally every campaign day.'
Assert-True ($politicalOverlaySource -match 'class CampaignPoliticalOverlayView : MapView' -and $politicalOverlaySource -match 'FadeStartAltitude = 580f' -and $politicalOverlaySource -match 'FadeEndAltitude = 740f') 'Political overlay is not gated by campaign-map zoom altitude.'
Assert-True ($politicalOverlaySource -match 'CampaignPoliticalSettlementNameplatePatch' -and $politicalOverlaySource -match 'HideAtAltitude = 650f' -and $politicalOverlaySource -match '____bindIsVisibleOnMap = false') 'Native settlement names are not suppressed at distant political zoom.'
Assert-True ($politicalOverlaySource -match 'holdings\.Average' -and $politicalOverlaySource -match 'WorldToScreenInsideUsableArea' -and $politicalOverlaySource -match 'collision') 'Kingdom labels are not centroid-projected with collision filtering.'
Assert-True ($politicalLabelPrefabSource -match 'Text="@Name"' -and $politicalLabelPrefabSource -match 'PositionXOffset="@ScreenX"' -and $politicalLabelPrefabSource -match 'DoNotAcceptEvents="true"') 'Kingdom labels are not non-interactive screen-projected UI.'
Assert-True ($politicalLabelPrefabSource -notmatch 'BlankWhiteSquare|#080808A8') 'Campaign kingdom names must use standalone gold lettering without dark background bars.'
Assert-True (($territoryFillSource + $politicalOverlaySource + $politicalLabelPrefabSource) -notmatch 'ArtemsBetterUIVisuals|BetterUIVisualsKingdom') 'Political fills and labels must be an independent implementation.'
Assert-True ($strategicKingdomLabelsSource -match 'BuildStrategicKingdomLabels' -and $strategicKingdomLabelsSource -match 'FindDominantKingdomCluster' -and $strategicKingdomLabelsSource -match 'StrategicKingdomClusterLinkDistance = 340f') 'Strategic Map country names are not positioned from live connected holdings.'
Assert-True ($strategicKingdomLabelsSource -match 'orderedKingdoms\.Sort' -and $strategicKingdomLabelsSource -match 'ResolveStrategicLabelOverlap') 'Strategic Map country-name placement is not deterministic and overlap-aware.'
Assert-True ($ledgerSource -match 'BuildStrategicKingdomLabels\(markerPoints\)') 'Strategic Map country names are not rebuilt with live border ownership.'
Assert-True ($prefabSource -match 'DataSource="\{StrategicKingdomLabels\}"' -and $prefabSource -match 'Color="@GoldColor"') 'Strategic Map country names are not rendered as gold lettering.'
$kingdomLabelSection = [regex]::Match($prefabSource, 'DataSource="\{StrategicKingdomLabels\}"[\s\S]*?DataSource="\{StrategicFriendlyArmies\}"').Value
Assert-True (([regex]::Matches($kingdomLabelSection, 'Text="@Name"')).Count -eq 1 -and $kingdomLabelSection -notmatch 'Color="@ShadowColor"') 'Strategic Map country names must use one text layer; an offset duplicate causes doubled lettering at low zoom.'
Assert-True ($strategicFriendlyArmiesSource -match 'party\.IsActive' -and $strategicFriendlyArmiesSource -match 'ReferenceEquals\(party\.Army\.LeaderParty, party\)' -and $strategicFriendlyArmiesSource -match 'DiplomacyHelper\.HasAllianceWithFaction') 'Strategic Map army markers are not limited to active friendly/allied army leaders.'
Assert-True ($strategicFriendlyArmiesSource -match 'MobileParty\.MainParty' -and $strategicFriendlyArmiesSource -match 'party\.ActualClan' -and $strategicFriendlyArmiesSource -match 'Your Party') 'Strategic Map markers do not include the player and active player-clan parties.'
Assert-True ($strategicFriendlyArmiesSource -match 'ProjectCampaignPositionToStrategicMap' -and $ledgerSource -match 'internal static Vec2 ProjectCampaignPositionToStrategicMap') 'Friendly armies do not use the calibrated Strategic Map projection.'
Assert-True ($prefabSource -match 'DataSource="\{StrategicFriendlyArmies\}"' -and $prefabSource -match 'Color="@MarkerColor"' -and $prefabSource -match 'Text="@Name"' -and $prefabSource -match 'Text="@Glyph"') 'Strategic Map friendly armies and clan parties are not rendered as labelled live markers.'
Assert-True ($prefabSource -match 'Text="P"[^>]*Color="#102018FF"' -and $prefabSource -match 'Text="Player party"' -and $prefabSource -match 'Color="#72B7FFFF"') 'Strategic Map legend is missing the player-party marker.'
Assert-True ($prefabSource -match 'Text="C"[^>]*Color="#102018FF"' -and $prefabSource -match 'Text="Clan party"' -and $prefabSource -match 'Color="#7DE8B0FF"') 'Strategic Map legend is missing the clan-party marker.'
Assert-True ($prefabSource -match 'Text="A"[^>]*Color="#102018FF"' -and $prefabSource -match 'Text="Friendly army"' -and $prefabSource -match 'Color="#65E89AFF"') 'Strategic Map legend is missing the friendly-army marker.'
Assert-True ($ledgerSource -match 'StrategicPartyLegendMinimumHeight = 198' -and $ledgerSource -match 'StrategicMapLegendSeparatorTop' -and $ledgerSource -match 'StrategicMapLegendHeight - StrategicPartyLegendBaseHeight') 'Strategic Map party legend does not reserve space without overlapping the summary.'
Assert-True ($subModuleSource -notmatch 'ArtemsBetterUIVisuals' -and $strategicFriendlyArmiesSource -notmatch 'Artem|BetterUIVisuals') 'Friendly-army markers must remain an independent implementation.'
Assert-True ($borderSource -notmatch 'CampaignStrategicProvinceBorderBehavior|AttachProvinceBorderBehavior|_provinceBorderBehavior' -and $subModuleSource -notmatch 'CampaignStrategicProvinceBorderBehavior|provinceBorders' -and $projectSource -notmatch 'Compile Include="CampaignStrategicProvinceBorderBehavior\.cs"') 'Campaign province contours must remain disabled and absent from the deployed assembly.'
Assert-True ($subModuleSource -match 'CampaignKingdomBorderBehavior politicalMap = new CampaignKingdomBorderBehavior\(\)' -and $subModuleSource -match 'campaignStarter\.AddBehavior\(politicalMap\)') 'Campaign border behavior is not registered in campaign startup.'
Assert-True ($projectSource -match 'Compile Include="CampaignKingdomBorderBehavior\.cs"') 'Campaign border behavior is not part of the main project.'
Assert-True ($projectSource -match 'Compile Include="CampaignMapTerrainGridCache\.cs"') 'Shared campaign terrain-grid cache is not part of the main project.'
Assert-True ($projectSource -match 'Compile Include="CampaignStrategicLandMask\.cs"') 'Campaign strategic land-mask source is not part of the main project.'
Assert-True ($projectSource -match 'Compile Include="CampaignPoliticalTerritoryFill\.cs"' -and $projectSource -match 'Compile Include="CampaignPoliticalOverlayView\.cs"' -and $projectSource -match 'Reference Include="SandBox\.View"') 'Political territory fill or overlay sources are not fully included in the main project.'
Assert-True ($projectSource -match 'Compile Include="CalendarStrategicKingdomLabels\.cs"') 'Strategic Map kingdom-label source is not included in the main project.'
Assert-True ($projectSource -match 'Compile Include="CalendarStrategicFriendlyArmies\.cs"') 'Strategic Map friendly-army source is not included in the main project.'
Assert-True ($worldCalendarScreenSource -match '_friendlyArmyRefreshElapsed >= 1f' -and $worldCalendarScreenSource -match 'RefreshStrategicFriendlyArmies') 'Friendly-army positions are not refreshed periodically while the Strategic Map is open.'
Assert-True ($ledgerSource -match 'GlowColor' -and $ledgerSource -match 'OnPropertyChangedWithValue\(GlowColor') 'Strategic settlement selection does not expose glow state changes.'
Assert-True ($prefabSource -match 'ImageWidget IsVisible="true"[^>]*Sprite="strategic_province_borders"[^>]*Color="#000000FF"') 'Strategic province border artwork is not enabled with an absolute-black tint.'
Assert-True (([regex]::Matches($prefabSource, 'IsVisible="@IsSelected"[^>]*Color="@GlowColor"')).Count -eq 4) 'Strategic settlement selection does not render four glow border bars.'

$ildasm = 'C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.7.2 Tools\x64\ildasm.exe'
if (Test-Path -LiteralPath $ildasm) {
    $assemblyText = & $ildasm $AssemblyPath /text
    Assert-True (@($assemblyText | Select-String 'CampaignKingdomBorderBehavior').Count -gt 0) 'Compiled test assembly does not contain the campaign border behavior.'
    Assert-True (@($assemblyText | Select-String 'CampaignStrategicProvinceBorderBehavior').Count -eq 0) 'Compiled test assembly still contains the disabled campaign province-border behavior.'
    Assert-True (@($assemblyText | Select-String 'CampaignPoliticalTerritoryFill').Count -gt 0) 'Compiled test assembly does not contain political territory fills.'
    Assert-True (@($assemblyText | Select-String 'CampaignPoliticalOverlayView').Count -gt 0) 'Compiled test assembly does not contain the zoomed-out political overlay.'
    Assert-True (@($assemblyText | Select-String 'CalendarStrategicKingdomLabelVM').Count -gt 0) 'Compiled test assembly does not contain dynamic Strategic Map kingdom labels.'
    Assert-True (@($assemblyText | Select-String 'CalendarStrategicFriendlyArmyVM').Count -gt 0) 'Compiled test assembly does not contain Strategic Map friendly-army markers.'
}

Write-Host 'Map border feature verification passed: dark saturated country fills, coast-following faction outlines, disabled campaign province contours, gold country names, live friendly armies/clan parties, and settlement glow are present.'
